runtime: custom
vm: true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
 - ^(.*/)?\.log$
